# This will run on Travis' 'new' container-based infrastructure
sudo: true

# Setup for Ubuntu Bionic (18.04)
dist: bionic

language:
  - python

python:
  - 3.6

# Environment variables
env:
  global:
    - PACKAGE_DIR: $HOME/packages
    - MINICONDA_DIR: $PACKAGE_DIR/miniconda
    - DOWNLOAD_URL: https://github.com/slaclab/cryo-det/releases/download/${TRAVIS_TAG}/rogue_${TRAVIS_TAG}.zip
    - secure: "l+cE3Ijlx/bJRTD/k72AfdWnVaxeBbO7HnuH/rMbMUP6NS02+/TIre9n9UqgfGJ2iSCXIU02+aOcGjCsbQd2y/r3ckHI3QQBDnb3bNmdNnhUVGkTcpycqs4SKvPe/AgijlwKBYeGoQwuntLj70AEQUbyjgj2rJ1FTkGTLrKZRgcfOPxs/Fdllc0OCwsX54kkk2LH54GYhWbCRSgPZmdTRCWXqswDPSTLxSOm5kgFtGwJGIXZhViF9JmRMpJwwBi+I7NC8gxEyg00IFZO2jwAV5U44nyKtl9kHNTdceBTDZn/b3pfpRRoe7YVgml48sf2a3fk4GUSTV9Xy7XVpu+1tzfvprCwZKfXIV0dFRKwpwa8yoj04MdKyYBaWUDxIarqRp5IKfuoZYIDiifHSoiq6YgPx/zzld8wUM2QPu41SFHfBMjpb9vyozViUk7jmVpEKkXRlMWdVSGb4MUv3BW49y/ITamCOPm1FgHxLmr24zYjneMSPoIj4wWD0OqcbtK7xQrVL11NBvjuKs4AJvIgU3rErLptKZWKRyk9+5ejzYoB8merahKmc++4nfONJuw9BlMKrA5dFz+Zfx4PUwlZifSCu8Fyb0IZJ4wOCRxnjcVZR3+IIqDfTVwwzSfaAQjjHcD5nX4m4UCk7nlh02sdMn90rojIaezmxZvY+qGnVKA="

# Install dependencies
addons:
  apt:
    packages:
      - python3

stages:
    - name: deploy_tag
      if: tag IS present

# Generate and deploy documentation
jobs:
  include:
    - &deploy-conda-stage       # Conda for linux
      stage: deploy_tag
      name: "Deploy Conda"
      env: CONDA_TOKEN=$CONDA_UPLOAD_TOKEN_DEV
      before_install:
        # Prepare folders
        - echo $DOWNLOAD_URL
        - mkdir -p $MINICONDA_DIR
        - mkdir -p $DOWNLOAD_DIR
        # on OSX rogue needs an older version of the MacOS SDK
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            git clone https://github.com/phracker/MacOSX-SDKs;
            sudo mv MacOSX-SDKs/MacOSX10.9.sdk /opt/;
            export CONDA_BUILD_SYSROOT=/opt/MacOSX10.9.sdk;
            export CONDA_BUILD=1;
          fi

      install:
        # Install Anaconda for the right architecture (linux or osx)
        - cd $MINICONDA_DIR
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
          else
            wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
          fi
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes
        - conda install conda-build anaconda-client conda-verify
        - conda update -q conda conda-build
        # Download and unzip tag zipfile
        - cd $TRAVIS_BUILD_DIR
        - wget -O file.zip $DOWNLOAD_URL
        - unzip file.zip

      script:
        # Build conda package
        - travis_wait 60 conda build --debug conda-recipe --output-folder bld-dir -c tidair-tag -c conda-forge

      after_success:
        # Upload conda package
        - anaconda -t $CONDA_UPLOAD_TOKEN_TAG upload bld-dir/`echo $TRAVIS_OS_NAME`-64/*.tar.bz2

    - <<: *deploy-conda-stage   # Conda for MacOS
      os: osx
      language: ruby  # osx does not support language=python

